import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from "next/image"
import Projects from './projects'

export default function Home({gitprofile,projects}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>PortFolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <div>
        <h1>{gitprofile.name}</h1>
        <h2>Intro: {gitprofile.bio}</h2>
        <h3>Full-stack Developer | FOSS | JavaScript | Typescript | NodeJS | Deno | ReactJS | HTML | CSS | Chakra-UI | MUI</h3>
        <a 
        download="Sagar_Wankhade_Resume"
        rel="noreferrer"
        href="../resume/Sagar_Wankhade_Resume.pdf"><button
        >Download Resume</button></a>
        <h4>
        
Full-Stack Web Development (Full Time)<br/>
Masai School, Bangalore<br/>
April 2022 -present<br/>
BE in Electrical and Electronics Engineering<br/>
PRMCEAM, Badnera, Maharashtra<br/>
July 2015 - January 2020
        </h4>
      </div>
      <Projects project={projects}></Projects>
      </div>
    </div>
  )
}

export async function getStaticProps(){

  let resp=await fetch("https://api.github.com/users/sagar1079")
  let data =await resp.json()

  let resp2=await fetch("https://api.github.com/search/repositories?q=user:sagar1079+fork:true&sort=updated&per_page=10&type=Repositories")
  let data2 =await resp2.json()

  return{
    props:{
      gitprofile:data, 
      projects:data2
    }
  }
}